Update upgrade-database script

diff --git a/manager/tools/upgrade-database b/manager/tools/upgrade-database
--- a/manager/tools/upgrade-database
+++ b/manager/tools/upgrade-database
@@ -14,6 +14,7 @@ secretsdir=./manager/secrets
 check_only=0
 appdir=/workspace
 migration_file="${migrationsdir}/0001_initial.py"
+backup_dir="${PWD}/scenescape_vol-backup"
 
 # Utility Functions
 run_table_rename() {
@@ -127,14 +128,19 @@ wait_for_container() {
 # Core functionality functions
 check_prerequisites() {
     # Check if database directories exist
-    if [ ! -d "${dbdir}" ] || [ ! -d "${migrationsdir}" ]; then
-        log_message "Database directories not found. No previous database installation detected."
-        log_message "No upgrade or migration needed."
+    if ! docker volume inspect scenescape_vol-db-backup >/dev/null 2>&1 || \
+       ! docker volume inspect scenescape_vol-migrations-backup >/dev/null 2>&1; then
+        log_message "Backup Docker volumes for database or migrations not found."
+        log_message "No previous database installation detected. No upgrade or migration needed."
         exit 0
     fi
-    
+
     # Get PostgreSQL versions
-    pg_db_version=$(cat ${dbdir}/PG_VERSION)
+    pg_db_version=$(docker run --rm \
+    -v scenescape_vol-db-backup:/var/lib/postgresql/data \
+    alpine:latest \
+    sh -c "cat /var/lib/postgresql/data/PG_VERSION")
+
     pg_new_version=$(docker run --rm ${scenescape_image} /bin/sh -c \
                      'echo -n PG_NEW_VERSION= ; ls /usr/lib/postgresql' \
                      | awk -F= '/PG_NEW_VERSION/{print $2}' | tr -d '\015')
@@ -193,6 +199,49 @@ check_migration_needed() {
 }
 
 backup_database() {
+    local pg_container="pg_backup"
+    local pg_uid=$(id -u)
+
+    # Check backup exists
+    if [ ! -d "${backup_dir}" ]; then
+        echo "Backup directory ${backup_dir} does not exist!"
+        return 1
+    fi
+
+    # adjust pg_hba.conf inside the volume
+    log_message "Temporarily configuring pg_hba.conf in the database volume for backup..."
+    docker run --rm \
+        -v scenescape_vol-db-backup:/var/lib/postgresql/data \
+        alpine sh -c "\
+            cp /var/lib/postgresql/data/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf-orig && \
+            echo 'local all all trust' > /var/lib/postgresql/data/pg_hba.conf && \
+            echo 'host all all 0.0.0.0/0 trust' >> /var/lib/postgresql/data/pg_hba.conf"
+
+    # Start a temporary PostgreSQL container to create SQL dump
+    log_message "Creating SQL backup from database volume..."
+    docker run \
+        --name ${pg_container} \
+        -e POSTGRES_PASSWORD="${dbpass}" \
+        -e POSTGRES_USER=scenescape \
+        -e POSTGRES_HOST_AUTH_METHOD=trust \
+        -v scenescape_vol-db-backup:/var/lib/postgresql/data \
+        --entrypoint="/bin/bash" \
+        -d \
+        postgres:${pg_db_version} \
+        -c "usermod --uid=${pg_uid} postgres ; id postgres ; exec docker-entrypoint.sh postgres"
+
+    wait_for_container ${pg_container} "database system is ready to accept connections"
+
+    log_message "Creating SQL backup of database..."
+    docker exec ${pg_container} /bin/bash -c 'su postgres -c "pg_dump -U scenescape"' > ${backup_dir}/scenescape_db_backup_${now}.psql
+
+    # Stop and remove temporary PostgreSQL container
+    docker stop ${pg_container} && docker rm ${pg_container}
+    log_message "SQL backup created at: ${backup_dir}/scenescape_db_backup_${now}.psql"
+    log_message "Backup process completed successfully."
+}
+
+backup_database_2() {
     local backup="${dbdir}-backup-${now}"
     local pg_container="pg_backup"
     local pg_uid=$(stat -c '%u' ${dbdir})
@@ -248,7 +297,7 @@ initialize_volumes() {
     log_message "Initializing migrations volume..."
     docker run --name ${temp_container} \
         -d \
-        -v ${PWD}/${migrationsdir}:/source/migrations \
+        -v scenescape_vol-migrations-backup:/source/migrations \
         -v ${PWD}/${mediadir}:/source/media \
         -v scenescape_vol-migrations:/dest/migrations \
         -v scenescape_vol-media:/dest/media \
@@ -335,9 +384,30 @@ run_migration() {
 
 # Main script execution
 main() {
-    if [[ -f "$migration_file" ]] && grep -q 'sscape' "$migration_file"; then
+
+    # Restore the database volume from tar backup
+    echo "==> Restoring database volume 'scenescape_vol-db'..."
+    docker volume create scenescape_vol-db-backup
+    docker run --rm \
+        -v scenescape_vol-db-backup:/volume \
+        -v $(pwd)/scenescape_vol-backup:/backup \
+        alpine sh -c "cd /volume && tar xzf /backup/scenescape_vol-db-backup.tar.gz"
+    echo "Database volume restored."
+
+    # Restore migrations volume if needed
+    echo "==> Restoring migrations volume 'scenescape_vol-migrations'..."
+    docker volume create scenescape_vol-migrations-backup
+    docker run --rm \
+        -v scenescape_vol-migrations-backup:/volume \
+        -v $(pwd)/scenescape_vol-backup:/backup \
+        alpine sh -c "cd /volume && tar xzf /backup/scenescape_vol-migrations-backup.tar.gz"
+    echo "Migrations volume restored."
+
+    if docker run --rm -v scenescape_vol-migrations-backup:/migrations alpine \
+        sh -c "grep -q 'sscape' /migrations/0001_initial.py"; then
         echo "'$migration_file' exists and contains 'sscape'. Renaming tables and sscape references in migration file..."
         run_table_rename
+
     else
         echo "No 'sscape' reference found in $migration_file, continuing upgrade..."
     fi
