Add clean up job

diff --git a/.github/workflows/coverity.yml b/.github/workflows/coverity.yml
--- a/.github/workflows/coverity.yml
+++ b/.github/workflows/coverity.yml
@@ -118,3 +118,14 @@ jobs:
       #          --form version="`date +%Y%m%d%H%M%S`" \
       #          --form description="GitHub Action upload" \
       #          https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT }}
+      
+      - name: "Clean runner"
+        if: always()
+        run: |
+          if [ -n "$GITHUB_WORKSPACE" ] && [ -d "$GITHUB_WORKSPACE" ]; then
+            find "$GITHUB_WORKSPACE" -type f -exec chmod u+rw {} \;
+            find "$GITHUB_WORKSPACE" -mindepth 1 -delete
+          else
+            echo "Error: GITHUB_WORKSPACE is not set or is not a directory" >&2
+            exit 1
+          fi
