added parameter for saving artifacts

diff --git a/.github/workflows/tests-all.yml b/.github/workflows/tests-all.yml
--- a/.github/workflows/tests-all.yml
+++ b/.github/workflows/tests-all.yml
@@ -20,6 +20,11 @@ on:
         required: false
         default: ""
         type: string
+      save_artifacts:
+        description: "Save artifacts from tests"
+        required: false
+        default: true
+        type: boolean
       cleanup:
         description: "Cleanup before running ALL tests"
         required: false
@@ -78,7 +83,7 @@ jobs:
           make run_basic_acceptance_tests
 
       - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
+        if: always() && inputs.save_artifacts
         uses: ./.github/actions/upload-artifacts
 
       - name: Cleanup
@@ -116,160 +121,160 @@ jobs:
           make run_functional_tests
 
       - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
+        if: always() && inputs.save_artifacts
         uses: ./.github/actions/upload-artifacts
 
       - name: Cleanup
         if: always()
         uses: ./.github/actions/cleanup
 
-  run_non_functional_tests:
-    runs-on: [all]
-    name: "Non-Functional Tests"
-    timeout-minutes: 20
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_non_functional_tests:
+  #   runs-on: [all]
+  #   name: "Non-Functional Tests"
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Non-Functional Tests
-        run: |
-          make clean-all
-          make run_non_functional_tests
+  #     - name: Run Non-Functional Tests
+  #       run: |
+  #         make clean-all
+  #         make run_non_functional_tests
 
-      - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && inputs.save_artifacts
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
-  run_metric_tests:
-    runs-on: [all]
-    name: "Metric Tests"
-    timeout-minutes: 20
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_metric_tests:
+  #   runs-on: [all]
+  #   name: "Metric Tests"
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Metric Tests
-        run: |
-          make clean-all
-          make run_metric_tests
+  #     - name: Run Metric Tests
+  #       run: |
+  #         make clean-all
+  #         make run_metric_tests
 
-      - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && inputs.save_artifacts
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
-  run_ui_tests:
-    runs-on: [all]
-    name: "UI Tests"
-    timeout-minutes: 45
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_ui_tests:
+  #   runs-on: [all]
+  #   name: "UI Tests"
+  #   timeout-minutes: 45
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run UI Tests
-        run: |
-          make clean-all
-          make run_ui_tests
+  #     - name: Run UI Tests
+  #       run: |
+  #         make clean-all
+  #         make run_ui_tests
 
-      - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && inputs.save_artifacts
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
-  run_unit_tests:
-    runs-on: [all]
-    name: "Unit Tests"
-    timeout-minutes: 20
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_unit_tests:
+  #   runs-on: [all]
+  #   name: "Unit Tests"
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Unit Tests
-        run: |
-          make clean-all
-          make run_unit_tests
+  #     - name: Run Unit Tests
+  #       run: |
+  #         make clean-all
+  #         make run_unit_tests
 
-      - name: Upload Logs and Reports
-        if: ${{ always() && github.event_name != 'workflow_call' }}
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && inputs.save_artifacts
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
