change log location

diff --git a/.github/workflows/tests-all.yml b/.github/workflows/tests-all.yml
--- a/.github/workflows/tests-all.yml
+++ b/.github/workflows/tests-all.yml
@@ -52,81 +52,83 @@ permissions:
   contents: read
 
 jobs:
-  run_basic_acceptance_tests:
-    runs-on: [all]
-    name: "Basic Acceptance Tests"
-    timeout-minutes: 45
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_basic_acceptance_tests:
+  #   runs-on: [all]
+  #   name: "Basic Acceptance Tests"
+  #   timeout-minutes: 45
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Basic Acceptance Tests
-        run: |
-          make clean-all
-          make run_basic_acceptance_tests > test_data/basic_acceptance_tests.log 2>&1
+  #     - name: Run Basic Acceptance Tests
+  #       run: |
+  #         make clean-all
+  #         mkdir test_data
+  #         make run_basic_acceptance_tests > test_data/basic_acceptance_tests.log 2>&1
 
-      - name: Upload Logs and Reports
-        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
-  run_functional_tests:
-    runs-on: [all]
-    name: "Functional Tests"
-    timeout-minutes: 55
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_functional_tests:
+  #   runs-on: [all]
+  #   name: "Functional Tests"
+  #   timeout-minutes: 55
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Functional Tests
-        run: |
-          make clean-all
-          make run_functional_tests > test_data/functional_tests.log 2>&1
+  #     - name: Run Functional Tests
+  #       run: |
+  #         make clean-all
+  #         mkdir test_data
+  #         make run_functional_tests > test_data/functional_tests.log 2>&1
 
-      - name: Upload Logs and Reports
-        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
   run_non_functional_tests:
     runs-on: [all]
@@ -156,6 +158,7 @@ jobs:
       - name: Run Non-Functional Tests
         run: |
           make clean-all
+          mkdir test_data
           make run_non_functional_tests > test_data/non_functional.log 2>&1
 
       - name: Upload Logs and Reports
@@ -166,43 +169,44 @@ jobs:
         if: always()
         uses: ./.github/actions/cleanup
 
-  run_metric_tests:
-    runs-on: [all]
-    name: "Metric Tests"
-    timeout-minutes: 20
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_metric_tests:
+  #   runs-on: [all]
+  #   name: "Metric Tests"
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Metric Tests
-        run: |
-          make clean-all
-          make run_metric_tests > test_data/metrics.log 2>&1
+  #     - name: Run Metric Tests
+  #       run: |
+  #         make clean-all
+  #         mkdir test_data
+  #         make run_metric_tests > test_data/metrics.log 2>&1
 
-      - name: Upload Logs and Reports
-        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
   run_ui_tests:
     runs-on: [all]
@@ -232,6 +236,7 @@ jobs:
       - name: Run UI Tests
         run: |
           make clean-all
+          mkdir test_data
           make run_ui_tests > test_data/ui_tests.log 2>&1
 
       - name: Upload Logs and Reports
@@ -242,53 +247,54 @@ jobs:
         if: always()
         uses: ./.github/actions/cleanup
 
-  run_unit_tests:
-    runs-on: [all]
-    name: "Unit Tests"
-    timeout-minutes: 20
-    steps:
-      - name: Remove test_data folder
-        run: |
-          sudo rm -rf test_data || true
+  # run_unit_tests:
+  #   runs-on: [all]
+  #   name: "Unit Tests"
+  #   timeout-minutes: 20
+  #   steps:
+  #     - name: Remove test_data folder
+  #       run: |
+  #         sudo rm -rf test_data || true
 
-      - name: Checkout Repository
-        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-          ref: ${{ inputs.ref }}
+  #     - name: Checkout Repository
+  #       uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+  #       with:
+  #         fetch-depth: 0
+  #         persist-credentials: false
+  #         ref: ${{ inputs.ref }}
 
-      - name: "Remove all Docker images"
-        if: ${{ github.event.inputs.cleanup == 'true' }}
-        uses: ./.github/actions/cleanup
-        with:
-          system-prune: "true"
+  #     - name: "Remove all Docker images"
+  #       if: ${{ github.event.inputs.cleanup == 'true' }}
+  #       uses: ./.github/actions/cleanup
+  #       with:
+  #         system-prune: "true"
 
-      - name: "Run Setup"
-        uses: ./.github/actions/setup-env
+  #     - name: "Run Setup"
+  #       uses: ./.github/actions/setup-env
 
-      - name: Run Unit Tests
-        run: |
-          make clean-all
-          make run_unit_tests > test_data/unit_tests.log 2>&1
+  #     - name: Run Unit Tests
+  #       run: |
+  #         make clean-all
+  #         mkdir test_data
+  #         make run_unit_tests > test_data/unit_tests.log 2>&1
 
-      - name: Upload Logs and Reports
-        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
-        uses: ./.github/actions/upload-artifacts
+  #     - name: Upload Logs and Reports
+  #       if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
+  #       uses: ./.github/actions/upload-artifacts
 
-      - name: Cleanup
-        if: always()
-        uses: ./.github/actions/cleanup
+  #     - name: Cleanup
+  #       if: always()
+  #       uses: ./.github/actions/cleanup
 
   generate_report:
     needs:
       [
-        run_basic_acceptance_tests,
-        run_functional_tests,
+        # run_basic_acceptance_tests,
+        # run_functional_tests,
         run_non_functional_tests,
-        run_metric_tests,
+        # run_metric_tests,
         run_ui_tests,
-        run_unit_tests,
+        # run_unit_tests,
       ]
     runs-on: ubuntu-latest
     name: "Generate Test Report"
@@ -319,7 +325,7 @@ jobs:
         run: |
           set +e
           touch test_results_summary.txt
-          log_files=("metrics.log" "non_functional.log" "functional_tests.log" "basic_acceptance_tests.log" "ui_tests.log" "unit_tests.log")
+          log_files=("test_data/metrics.log" "test_data/non_functional.log" "test_data/functional_tests.log" "test_data/basic_acceptance_tests.log" "test_data/ui_tests.log" "test_data/unit_tests.log")
           for log_file in "${log_files[@]}"; do
             grep -Erh "NEX-T.*: (PASS|FAIL)" $log_file | sed 's/\(NEX-T[0-9]*\)[^:]*\(: .*\)/\1\2/' >> test_results_summary.txt
           done
